/**
 * /robots.txt — Auto-generated by Next.js at build time (next build)
 * Hướng dẫn Google crawler, trỏ tới sitemap.xml
 */
import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://inlygiaRe.vn";

  return {
    rules: [
      {
        // Tất cả bot: cho phép index, chặn admin + API
        userAgent: "*",
        allow: ["/", "/blog/", "/tin-tuc/chuyen-muc/"],
        disallow: ["/admin", "/admin/", "/api/", "/_next/", "/studio"],
      },
      {
        // Googlebot: ưu tiên cấu hình riêng
        userAgent: "Googlebot",
        allow: ["/", "/blog/", "/tin-tuc/chuyen-muc/"],
        disallow: ["/admin", "/admin/", "/api/"],
      },
      {
        // Bing
        userAgent: "Bingbot",
        allow: ["/", "/blog/"],
        disallow: ["/admin", "/api/"],
      },
    ],
    // Next.js tự export /sitemap.xml khi next build
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}

